-- MAGNITUDE ANALYSIS --

--Find the total customers by country 
SELECT COUNT(customer_id) as total_customers,
		country
FROM gold.dim_customers
GROUP BY country;

--Find the total customers by gender
SELECT COUNT(customer_id) as total_customers,
	   gender
FROM gold.dim_customers
GROUP BY gender;

--Find total products by category
SELECT COUNT(product_id) as total_products,
	   category 
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_id) ;

--Average cost in each category
SELECT AVG(cost) as average_cost,
	   category
FROM gold.dim_products
group by category
ORDER by AVG(cost) DESC;

--Total revenue generated for each category
SELECT 
	SUM(fs.sales_amount) as revenue,
	dp.category
from gold.fact_sales fs
JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
GROUP BY dp.category;

--Total revenue generated by each customer
SELECT 
	SUM(fs.sales_amount) as total_revenue,
	dc.customer_key,
	dc.first_name,
	dc.last_name
from gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name,dc.last_name
ORDER by total_revenue DESC;

--What is the distribution of items sold across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
